/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface CrowdfundFactoryInterface extends ethers.utils.Interface {
  functions: {
    "createCrowdfund(address[],uint256[],bytes32)": FunctionFragment;
    "logic()": FunctionFragment;
    "parameters()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createCrowdfund",
    values: [string[], BigNumberish[], BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "logic", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "parameters",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createCrowdfund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "logic", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "parameters", data: BytesLike): Result;

  events: {
    "CrowdfundDeployed(address,bytes32,uint256[],address[])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CrowdfundDeployed"): EventFragment;
}

export type CrowdfundDeployedEvent = TypedEvent<
  [string, string, BigNumber[], string[]] & {
    crowdfundProxy: string;
    poolId: string;
    fundingParams: BigNumber[];
    addresses: string[];
  }
>;

export class CrowdfundFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CrowdfundFactoryInterface;

  functions: {
    createCrowdfund(
      addresses_: string[],
      fundingParams_: BigNumberish[],
      poolId_: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    logic(overrides?: CallOverrides): Promise<[string]>;

    parameters(
      overrides?: CallOverrides
    ): Promise<[string] & { poolId: string }>;
  };

  createCrowdfund(
    addresses_: string[],
    fundingParams_: BigNumberish[],
    poolId_: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  logic(overrides?: CallOverrides): Promise<string>;

  parameters(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    createCrowdfund(
      addresses_: string[],
      fundingParams_: BigNumberish[],
      poolId_: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    logic(overrides?: CallOverrides): Promise<string>;

    parameters(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "CrowdfundDeployed(address,bytes32,uint256[],address[])"(
      crowdfundProxy?: null,
      poolId?: null,
      fundingParams?: null,
      addresses?: null
    ): TypedEventFilter<
      [string, string, BigNumber[], string[]],
      {
        crowdfundProxy: string;
        poolId: string;
        fundingParams: BigNumber[];
        addresses: string[];
      }
    >;

    CrowdfundDeployed(
      crowdfundProxy?: null,
      poolId?: null,
      fundingParams?: null,
      addresses?: null
    ): TypedEventFilter<
      [string, string, BigNumber[], string[]],
      {
        crowdfundProxy: string;
        poolId: string;
        fundingParams: BigNumber[];
        addresses: string[];
      }
    >;
  };

  estimateGas: {
    createCrowdfund(
      addresses_: string[],
      fundingParams_: BigNumberish[],
      poolId_: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    logic(overrides?: CallOverrides): Promise<BigNumber>;

    parameters(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    createCrowdfund(
      addresses_: string[],
      fundingParams_: BigNumberish[],
      poolId_: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    logic(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    parameters(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
