/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVault__factory>;
    getContractFactory(
      name: "CrowdfundFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CrowdfundFactory__factory>;
    getContractFactory(
      name: "CrowdfundLogic",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CrowdfundLogic__factory>;
    getContractFactory(
      name: "CrowdfundProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CrowdfundProxy__factory>;
    getContractFactory(
      name: "ICrowdfundFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICrowdfundFactory__factory>;
    getContractFactory(
      name: "CrowdfundStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CrowdfundStorage__factory>;
    getContractFactory(
      name: "ExampleERC20Token",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ExampleERC20Token__factory>;

    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IVault",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IVault>;
    getContractAt(
      name: "CrowdfundFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CrowdfundFactory>;
    getContractAt(
      name: "CrowdfundLogic",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CrowdfundLogic>;
    getContractAt(
      name: "CrowdfundProxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CrowdfundProxy>;
    getContractAt(
      name: "ICrowdfundFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ICrowdfundFactory>;
    getContractAt(
      name: "CrowdfundStorage",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CrowdfundStorage>;
    getContractAt(
      name: "ExampleERC20Token",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ExampleERC20Token>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
