name: Deploy to Skynet

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: yarn
      - run: yarn build && yarn export

      - name: "Deploy to Skynet"
        uses: SkynetLabs/deploy-to-skynet-action@v2
        with:
          upload-dir: packages/frontend/out
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ secrets.SKYNET_REGISTRY_SEED || '' }}
